import { dialog, BrowserWindow } from 'electron';
import * as fs from 'fs/promises';
import * as path from 'path';
import { ElectroLoomProject } from '../shared/types';

export async function showOpenDialog(parentWindow: BrowserWindow): Promise<string | null> {
  const result = await dialog.showOpenDialog(parentWindow, {
    title: 'Open Simudino Project',
    filters: [
      { name: 'Simudino Projects', extensions: ['simudino'] },
      { name: 'All Files', extensions: ['*'] },
    ],
    properties: ['openFile'],
  });

  if (result.canceled || result.filePaths.length === 0) {
    return null;
  }

  return result.filePaths[0];
}

export async function showSaveDialog(parentWindow: BrowserWindow, defaultName?: string): Promise<string | null> {
  const result = await dialog.showSaveDialog(parentWindow, {
    title: 'Save Simudino Project',
    defaultPath: defaultName ? `${defaultName}.simudino` : 'untitled.simudino',
    filters: [
      { name: 'Simudino Projects', extensions: ['simudino'] },
      { name: 'All Files', extensions: ['*'] },
    ],
  });

  if (result.canceled || !result.filePath) {
    return null;
  }

  return result.filePath;
}

export async function loadProject(filePath: string): Promise<ElectroLoomProject> {
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    const project: ElectroLoomProject = JSON.parse(content);
    
    // Basic validation
    if (!project.id || !project.name || !project.circuit || !project.sketch) {
      throw new Error('Invalid project file structure');
    }
    
    return project;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to load project: ${error.message}`);
    }
    throw new Error('Failed to load project: Unknown error');
  }
}

export async function saveProject(filePath: string, project: ElectroLoomProject): Promise<void> {
  try {
    // Ensure directory exists
    const dir = path.dirname(filePath);
    await fs.mkdir(dir, { recursive: true });
    
    // Update project metadata
    const projectToSave: ElectroLoomProject = {
      ...project,
      metadata: {
        ...project.metadata,
        modified: new Date().toISOString(),
      },
    };
    
    const content = JSON.stringify(projectToSave, null, 2);
    await fs.writeFile(filePath, content, 'utf-8');
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to save project: ${error.message}`);
    }
    throw new Error('Failed to save project: Unknown error');
  }
}

export async function createNewProject(name: string): Promise<ElectroLoomProject> {
  const now = new Date().toISOString();
  const projectId = `project_${Date.now()}`;
  
  const newProject: ElectroLoomProject = {
    id: projectId,
    name,
    version: '1.0.0',
    circuit: {
      id: `circuit_${Date.now()}`,
      name: `${name} Circuit`,
      version: '1.0.0',
      board: {
        type: 'uno',
        name: 'Arduino Uno R3',
        microcontroller: 'ATmega328P',
        digitalPins: 14,
        analogPins: 6,
        flashMemory: 32768,
        sramMemory: 2048,
        eepromMemory: 1024,
        clockSpeed: 16000000,
        serialPorts: 1,
      },
      components: [],
      wires: [],
      metadata: {
        created: now,
        modified: now,
        author: 'Simudino User',
      },
    },
    sketch: {
      id: `sketch_${Date.now()}`,
      name: `${name} Sketch`,
      code: `// ${name} Arduino Sketch
// Generated by Simudino

void setup() {
  // Initialize serial communication
  Serial.begin(9600);
  
  // Add your setup code here
}

void loop() {
  // Add your main code here
  
  delay(1000);
}`,
      libraries: [],
      boardConfig: 'uno',
      metadata: {
        created: now,
        modified: now,
        author: 'Simudino User',
      },
    },
    configuration: {
      simulation: {
        timeStep: 1,
        maxRunTime: 300000, // 5 minutes
        enableDebugging: true,
        enableProfiling: false,
      },
      virtualPort: {
        enabled: false,
        baudRate: 9600,
        dataBits: 8,
        stopBits: 1,
        parity: 'none',
      },
      display: {
        theme: 'light',
        gridEnabled: true,
        snapToGrid: true,
        showPinLabels: true,
      },
    },
    metadata: {
      created: now,
      modified: now,
      author: 'Simudino User',
      description: `Arduino project created with Simudino`,
      tags: ['arduino', 'simulation'],
    },
  };
  
  return newProject;
}

export async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

export async function createBackup(filePath: string): Promise<string> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupPath = `${filePath}.backup.${timestamp}`;
  
  try {
    await fs.copyFile(filePath, backupPath);
    return backupPath;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to create backup: ${error.message}`);
    }
    throw new Error('Failed to create backup: Unknown error');
  }
}